# theme: jekyll-theme-cayman

# Site settings
title: Hjh Blog
SEOTitle: 黄金海的博客 | Hjh Blog
header-img: img/home-bg.png
email: 2538082724@qq.com
description: "个人发展 | 黄金海，Engineer | hjh的个人博客呀"
keyword: "黄金海，just try it"
url: "https://tf.huangjinhai.space/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'


# avatar and Favicon
# avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: favicon.ico


# Sidebar settings
sidebar: true                          # whether or not using Sidebar.
sidebar-about-description: "Learn to do"
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# SNS settings
RSS: false
weibo_username:     false
zhihu_username:     false
github_username:    huangjinhai12


# Build settings
paginate: 10
plugins: [jekyll-paginate]
# gems: [jekyll-paginate]


# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 1845822a954cfa17811f                            #生成的clientID
  clientSecret: d0bbcc2289d9aad5260073cb74489a92766aa0d0   #生成的clientSecret
  repo: huangjinhai12.github.io    #仓库名称
  owner: huangjinhai12    #github用户名
  admin: huangjinhai12
  # distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Friends
friends: [
  {
    title: "hjh's github",
    href: "https://huangjinhai12.github.io/"
  }
]
